name: Repository Spotlight

on:
  schedule:
    - cron: '0 3 * * 0' # Every Sunday at 03:00 UTC
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  spotlight:
    uses: actionsforge/actions-repo-spotlight@v1
    with:
      token: ${{ secrets.GH_SPOTLIGHT_TOKEN }}
      limit: 6
      delay: 300
      min_views: 0
      include_forks: false
      include_archived: false
